# User-defined parameters. The parameter suggestions are all written here
Params:
  process_name: &process_name recommend_stock
  project: &project $Env{STOCK_PROJECT}

# The variable definitions in the YAML file are used for the following configuration
Varible:
  local_params: &local_params { "prop": "project", "direct": "IN", "type": "VARCHAR", "value": "${project}"}

# Define the process
Process:
  name: *process_name
  param:
      project: *project

# Define the tasks under the process
Tasks:
  - 
    TaskType: Shell
    params:
      name: recommend_stock 
      command: |
                export PYTHONPATH=${project}
                source ${project}/env/bin/activate
                python -m dmsa.evaluate.inference_sagemaker \
                      --evaluate_data s3://ds-stock/stock_out/inference.csv \
                      --top_n 10
      local_params: 
        - *local_params 

