# User-defined parameters. The parameter suggestions are all written here
Params:
  process_name: &process_name run_system
  project: &project $Env{STOCK_PROJECT}

# The variable definitions in the YAML file are used for the following configuration
Varible:
  local_params: &local_params { "prop": "project", "direct": "IN", "type": "VARCHAR", "value": "${project}"}

# Define the process
Process:
  name: *process_name
  param:
      project: *project
  run: False

# Define the tasks under the process
Tasks:
  - 
    TaskType: SubProcess 
    params:
      name: prepare_datas
      process_definition_name: prepare_datas
  - 
    TaskType: SubProcess
    dependencies: [prepare_datas]
    params:
      name: training_model 
      process_definition_name: training_model
  - 
    TaskType: SubProcess
    dependencies: [training_model]
    params:
      name: recommend_stock 
      process_definition_name: recommend_stock 
