params:
  process_name: &process_name training_model
  project: &project "/home/lucky/WhaleOps/DolphinScheduler-MLOps-Stock-Analysis"
  s3_data_path: &s3_data_path "s3://sagemaker-us-west-2-557980067422/dataset/dataset2.csv"

Varible:
  s3_local_params: &s3_local_params { "prop": "s3_data_path", "direct": "IN", "type": "VARCHAR", "value": *s3_data_path}

Process:
  name: *process_name
  param:
      project: *project
  execute: run

Tasks:
  - 
    TaskType: Shell
    params:
      name: prepare_data 
      command: File("pydolphin/config/scripts/prepare_data.sh") 
      local_params: 
        - *s3_local_params
        - { "prop": "project", "direct": "IN", "type": "VARCHAR", "value": "${project}"}

  - 
    TaskType: SageMaker
    dependencies: [prepare_data]
    params:
      name: sagemaker
      sagemaker_request_json: File("pydolphin/config/scripts/sagemaker_params.json") 
      local_params: 
        - *s3_local_params
